using Microsoft.VisualStudio.TestTools.UnitTesting;
using MkDocsSharp.MDGen.MSBuild;

namespace Example.SystemTests;

/// <summary>
/// System tests that verify end-to-end document generation from the example project.
/// These tests use the actual XML documentation output from the Example.XmlDocSamples project.
/// </summary>
[TestClass]
public class DocumentGenerationTests
{
    private string _testDir = null!;
    private string _xmlDocPath = null!;

    [TestInitialize]
    public void Setup()
    {
        _testDir = Path.Combine(Path.GetTempPath(), $"DocGenTests_{Guid.NewGuid():N}");
        Directory.CreateDirectory(_testDir);

        // The XML documentation file from the example project
        // In a real build, this would be generated by the compiler
        _xmlDocPath = Path.Combine(AppContext.BaseDirectory, "Example.XmlDocSamples.xml");
    }

    [TestCleanup]
    public void Cleanup()
    {
        if (Directory.Exists(_testDir))
        {
            try
            {
                Directory.Delete(_testDir, recursive: true);
            }
            catch
            {
                // Ignore cleanup failures in tests
            }
        }
    }

    [TestMethod]
    public void GenerateMarkdown_FromExampleProject_ProducesValidOutput()
    {
        // Skip if XML doc file doesn't exist (e.g., in CI without full build)
        if (!File.Exists(_xmlDocPath))
        {
            Assert.Inconclusive($"XML documentation file not found: {_xmlDocPath}. Run a full build first.");
            return;
        }

        // Arrange
        var logger = new TestLogger();
        var outputDir = Path.Combine(_testDir, "output");
        Directory.CreateDirectory(outputDir);

        var generator = new MarkdownGenerator(logger)
        {
            InputXmlFiles = new[] { _xmlDocPath },
            DocumentationPath = outputDir,
            MergeFiles = false,
            WarnOnUnexpectedTag = true
        };

        // Act
        var result = generator.Execute();

        // Assert
        Assert.IsTrue(result, $"Generation failed. Errors: {string.Join(", ", logger.Errors)}");
        Assert.AreEqual(1, generator.GeneratedMDFiles.Count, "Should generate one markdown file");

        var mdContent = File.ReadAllText(generator.GeneratedMDFiles[0]);
        
        // Verify key content is present
        Assert.IsTrue(mdContent.Contains("BasicClass"), "Should document BasicClass");
        Assert.IsTrue(mdContent.Contains("GenericContainer"), "Should document generic types");
        Assert.IsTrue(mdContent.Contains("Point2D"), "Should document structs");
        Assert.IsTrue(mdContent.Contains("Person"), "Should document records");
        Assert.IsTrue(mdContent.Contains("IRepository"), "Should document interfaces");
        Assert.IsTrue(mdContent.Contains("DayOfWeek"), "Should document enums");
    }

    [TestMethod]
    public void GenerateMarkdown_ContainsMethodSignatures()
    {
        if (!File.Exists(_xmlDocPath))
        {
            Assert.Inconclusive($"XML documentation file not found: {_xmlDocPath}");
            return;
        }

        // Arrange
        var logger = new TestLogger();
        var outputDir = Path.Combine(_testDir, "output");
        Directory.CreateDirectory(outputDir);

        var generator = new MarkdownGenerator(logger)
        {
            InputXmlFiles = new[] { _xmlDocPath },
            DocumentationPath = outputDir,
            MergeFiles = false
        };

        // Act
        generator.Execute();

        // Assert
        var mdContent = File.ReadAllText(generator.GeneratedMDFiles[0]);

        // Check for documented method parameters
        Assert.IsTrue(mdContent.Contains("param") || mdContent.Contains("Parameter"),
            "Should include parameter documentation");
        Assert.IsTrue(mdContent.Contains("returns") || mdContent.Contains("Returns"),
            "Should include return value documentation");
    }

    [TestMethod]
    public void GenerateMarkdown_WithMerge_CombinesWithExistingDocs()
    {
        if (!File.Exists(_xmlDocPath))
        {
            Assert.Inconclusive($"XML documentation file not found: {_xmlDocPath}");
            return;
        }

        // Arrange
        var logger = new TestLogger();
        var outputDir = Path.Combine(_testDir, "output");
        var mergedFile = Path.Combine(_testDir, "API.md");
        Directory.CreateDirectory(outputDir);

        // Create an existing markdown file
        var existingContent = @"# Example API Documentation

This is the main documentation file for the example project.

## Overview

This project demonstrates XML documentation patterns.

---
";
        File.WriteAllText(Path.Combine(outputDir, "README.md"), existingContent);

        var generator = new MarkdownGenerator(logger)
        {
            InputXmlFiles = new[] { _xmlDocPath },
            DocumentationPath = outputDir,
            MergeFiles = true,
            OutputFile = mergedFile
        };

        // Act
        var result = generator.Execute();

        // Assert
        Assert.IsTrue(result, $"Generation failed. Errors: {string.Join(", ", logger.Errors)}");
        Assert.IsTrue(File.Exists(mergedFile), "Merged file should exist");

        var mergedContent = File.ReadAllText(mergedFile);
        Assert.IsTrue(mergedContent.Contains("Example API Documentation"),
            "Should contain original content");
        Assert.IsTrue(mergedContent.Contains("BasicClass") || mergedContent.Contains("TestClass"),
            "Should contain generated API content");
    }

    [TestMethod]
    public void GenerateMarkdown_OutputIsValidMarkdown()
    {
        if (!File.Exists(_xmlDocPath))
        {
            Assert.Inconclusive($"XML documentation file not found: {_xmlDocPath}");
            return;
        }

        // Arrange
        var logger = new TestLogger();
        var outputDir = Path.Combine(_testDir, "output");
        Directory.CreateDirectory(outputDir);

        var generator = new MarkdownGenerator(logger)
        {
            InputXmlFiles = new[] { _xmlDocPath },
            DocumentationPath = outputDir,
            MergeFiles = false
        };

        // Act
        generator.Execute();

        // Assert
        var mdContent = File.ReadAllText(generator.GeneratedMDFiles[0]);

        // Basic markdown structure validation
        Assert.IsTrue(mdContent.Contains("#"), "Should contain headers");
        Assert.IsFalse(mdContent.Contains("<?xml"), "Should not contain raw XML declaration");
        Assert.IsFalse(mdContent.Contains("</member>"), "Should not contain raw XML tags");
        
        // Check for proper markdown formatting
        var lines = mdContent.Split('\n');
        var hasHeaders = lines.Any(l => l.TrimStart().StartsWith('#'));
        Assert.IsTrue(hasHeaders, "Should have markdown headers");
    }

    [TestMethod]
    public void GenerateMarkdown_HandlesAllXmlDocTags()
    {
        if (!File.Exists(_xmlDocPath))
        {
            Assert.Inconclusive($"XML documentation file not found: {_xmlDocPath}");
            return;
        }

        // Arrange
        var logger = new TestLogger();
        var outputDir = Path.Combine(_testDir, "output");
        Directory.CreateDirectory(outputDir);

        var generator = new MarkdownGenerator(logger)
        {
            InputXmlFiles = new[] { _xmlDocPath },
            DocumentationPath = outputDir,
            MergeFiles = false,
            WarnOnUnexpectedTag = true
        };

        // Act
        var result = generator.Execute();

        // Assert
        Assert.IsTrue(result, "Should handle all tags without errors");
        
        // Log any warnings for review
        if (logger.Warnings.Any())
        {
            Console.WriteLine("Warnings during generation:");
            foreach (var warning in logger.Warnings)
            {
                Console.WriteLine($"  - {warning}");
            }
        }
    }

    [TestMethod]
    public void GenerateMarkdown_ContainsAllXmlDocTagOutputs()
    {
        if (!File.Exists(_xmlDocPath))
        {
            Assert.Inconclusive($"XML documentation file not found: {_xmlDocPath}");
            return;
        }

        // Arrange
        var logger = new TestLogger();
        var outputDir = Path.Combine(_testDir, "output");
        Directory.CreateDirectory(outputDir);

        var generator = new MarkdownGenerator(logger)
        {
            InputXmlFiles = new[] { _xmlDocPath },
            DocumentationPath = outputDir,
            MergeFiles = false,
            WarnOnUnexpectedTag = true
        };

        // Act
        var result = generator.Execute();
        Assert.IsTrue(result, $"Generation failed. Errors: {string.Join(", ", logger.Errors)}");
        
        var mdContent = File.ReadAllText(generator.GeneratedMDFiles[0]);

        // Verify outputs from all supported XML doc tags:
        
        // summary - should produce type/method descriptions
        Assert.IsTrue(mdContent.Contains("Demonstrates"), "summary tag should produce descriptions");
        
        // remarks - should produce blockquotes (>)
        Assert.IsTrue(mdContent.Contains(">"), "remarks tag should produce blockquotes");
        
        // example - should produce Example header
        Assert.IsTrue(mdContent.Contains("Example:"), "example tag should produce Example header");
        
        // code - should produce code blocks (```)
        Assert.IsTrue(mdContent.Contains("```"), "code tag should produce code blocks");
        
        // param - should produce parameter table
        Assert.IsTrue(mdContent.Contains("|Name | Description |"), "param tag should produce parameter table");
        
        // typeparam - should produce type parameter table
        Assert.IsTrue(mdContent.Contains("|T:"), "typeparam tag should produce type parameter rows");
        
        // returns - should produce Returns section
        Assert.IsTrue(mdContent.Contains("**Returns**:"), "returns tag should produce Returns section");
        
        // exception - should produce exception links
        Assert.IsTrue(mdContent.Contains("ArgumentNullException") || mdContent.Contains("ArgumentException"), 
            "exception tag should document exceptions");
        
        // value - should produce Value section
        Assert.IsTrue(mdContent.Contains("**Value**:"), "value tag should produce Value section");
        
        // c - should produce inline code (backticks)
        Assert.IsTrue(mdContent.Contains("`true`") || mdContent.Contains("`false`"), 
            "c tag should produce inline code");
        
        // see cref - should produce links
        Assert.IsTrue(mdContent.Contains("[`") && mdContent.Contains("`]("), 
            "see cref tag should produce markdown links");
        
        // see langword - should produce keyword formatting
        Assert.IsTrue(mdContent.Contains("`null`"), "see langword tag should format null keyword");
        Assert.IsTrue(mdContent.Contains("`async`") || mdContent.Contains("`await`"), 
            "see langword tag should format async keywords");
        
        // seealso - should produce See also section
        Assert.IsTrue(mdContent.Contains("**See also**:"), "seealso tag should produce See also section");
        
        // para - should produce paragraph breaks (multiple newlines in remarks)
        Assert.IsTrue(mdContent.Contains("\n\n"), "para tag should produce paragraph breaks");
        
        // list/item - should produce bullet points
        Assert.IsTrue(mdContent.Contains("- "), "list/item tags should produce bullet points");
        
        // paramref - should produce parameter references
        Assert.IsTrue(mdContent.Contains("`input`") || mdContent.Contains("`value`"), 
            "paramref tag should reference parameter names");
        
        // typeparamref - should produce type parameter references  
        Assert.IsTrue(mdContent.Contains("`T`") || mdContent.Contains("`TValue`"), 
            "typeparamref tag should reference type parameter names");
        
        // inheritdoc - should produce inheritance note
        Assert.IsTrue(mdContent.Contains("Inherits documentation"), 
            "inheritdoc tag should produce inheritance note");
        
        // Verify member type prefixes are expanded
        Assert.IsTrue(mdContent.Contains("## Type "), "Type members should have Type prefix");
        Assert.IsTrue(mdContent.Contains("#### Method "), "Method members should have Method prefix");
        Assert.IsTrue(mdContent.Contains("#### Property "), "Property members should have Property prefix");
        Assert.IsTrue(mdContent.Contains("#### Field ") || mdContent.Contains("Field"), 
            "Field members should be documented");
        Assert.IsTrue(mdContent.Contains("#### Event ") || mdContent.Contains("Event"), 
            "Event members should be documented");
    }

    /// <summary>
    /// Test logger for system tests.
    /// </summary>
    private class TestLogger : IMarkdownGeneratorLogger
    {
        public List<string> Errors { get; } = new();
        public List<string> Warnings { get; } = new();

        public void LogError(string message) => Errors.Add(message);
        public void LogWarning(Exception exception) => Warnings.Add(exception.Message);
        public void LogError(Exception exception) => Errors.Add(exception.ToString());
    }
}
